# 1. Pandas DataFrame

In [1]:
!pip install pandas

In [10]:
import pandas as pd
import numpy as np

In [5]:
np.arange(0,20) #creating random 20 integers

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
np.arange(0,20).reshape(5,4) #converting above random int to 2 dimensional data with 5 rows 4 column

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [17]:
  ## Create data Frame
df = pd.DataFrame(data = np.arange(0,20).reshape(5,4), #press Shift + tab after DataFrame and before "(" to see all the details
             index = ["Row1","Row2","Row3","Row4","Row5"], #index for rows
             columns = ["Col1","Col2","Col3","Col4"])     #index for columns

In [18]:
df

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [19]:
df.head() #display top 5 records

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [20]:
df.tail() #display bottom 5 records

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [21]:
df.head(3) #display top 3 records same with tail

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11

In [22]:
 type(df)      #Dtaframe is type of data Structure

pandas.core.frame.DataFrame

In [23]:
df.info()     #to get the all the information regarding columns

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Col1    5 non-null      int32
 1   Col2    5 non-null      int32
 2   Col3    5 non-null      int32
 3   Col4    5 non-null      int32
dtypes: int32(4)
memory usage: 120.0+ bytes


In [24]:
df.describe() #to get all statistical data #only integer type will be displayed

Col1       Col2       Col3       Col4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

# Indexing

1. direct by using column name
2. rowindex named "loc"  #loc = location
3. rowindex columnindex number named "iloc" --->   #iloc = indexlocation

# 1.direct by using column name

In [25]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [26]:
df["Col1"] #to display only 1 column

Row1     0
Row2     4
Row3     8
Row4    12
Row5    16
Name: Col1, dtype: int32

In [29]:
type(df["Col1"]) ## VV Imp --> single colum or row datas are called "SERIES" and Mulitple Data Columns are called "DataFrame"

pandas.core.series.Series

In [27]:
df[["Col1","Col2","Col3"]] #to display multiple colums we need to use double sq bracket or nested bracket--V imp

Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6
Row3     8     9    10
Row4    12    13    14
Row5    16    17    18

In [28]:
type(df[["Col1","Col2","Col3"]]) ## VV Imp --> single colum or row datas are called "SERIES" and Mulitple Data Columns are called "DataFrame"

pandas.core.frame.DataFrame

# 2. Rowindex named "loc"

In [30]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [32]:
df.loc["Row3"] #to get all data of row3

Col1     8
Col2     9
Col3    10
Col4    11
Name: Row3, dtype: int32

In [33]:
type(df.loc["Row3"])  ## VV Imp --> single colum or row datas are called "SERIES" and Mulitple Data Columns are called "DataFrame"

pandas.core.series.Series

In [34]:
df.loc[["Row3","Row4"]]

Col1  Col2  Col3  Col4
Row3     8     9    10    11
Row4    12    13    14    15

In [35]:
type(df.loc[["Row3","Row4"]])## VV Imp --> single colum or row datas are called "SERIES" and Mulitple Data Columns are called "DataFrame"

pandas.core.frame.DataFrame

# 3. rowindex columnindex number named "iloc"

In [36]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [ ]:
#by default index number starts at zero for both column and rows

In [ ]:
#df.iloc["row details"  , "Colum details"]
#df.iloc["from row" : "to row" , "From Column" : "To Column"] ---> we will be using index number here

In [37]:
df.iloc[2:4,0:2]  #we have used index number #plz check the output

Col1  Col2
Row3     8     9
Row4    12    13

In [38]:
df.iloc[2:,1:] #if we dont give the last number it will print till end

Col2  Col3  Col4
Row3     9    10    11
Row4    13    14    15
Row5    17    18    19

In [39]:
df.iloc[:2,:3] #if we dont give the first number it will print from start

Col1  Col2  Col3
Row1     0     1     2
Row2     4     5     6

In [40]:
df.iloc[: , : : 3] #plz check this 

Col1  Col4
Row1     0     3
Row2     4     7
Row3     8    11
Row4    12    15
Row5    16    19

In [41]:
df.iloc[2:,1:].values  #to convert data froame to array

array([[ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

# Basic Operations

In [43]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [44]:
df.isnull().sum() #to check null values

Col1    0
Col2    0
Col3    0
Col4    0
dtype: int64

In [48]:
dd = pd.DataFrame(data = [[1,np.nan,2],[1,3,4]],  #np.nan is to inset null value
             index = ["Row1","Row2"], #index for rows
             columns = ["Col1","Col2","Col3"])     #index for columns

In [49]:
dd

Col1  Col2  Col3
Row1     1   NaN     2
Row2     1   3.0     4

In [50]:
dd.isnull().sum()   #in col2 i have 1 null value

Col1    0
Col2    1
Col3    0
dtype: int64

In [52]:
dd.isnull()

Col1   Col2   Col3
Row1  False   True  False
Row2  False  False  False

In [53]:
dd["Col3"].value_counts() #count the number of value present in column3

2    1
4    1
Name: Col3, dtype: int64

In [54]:
dd["Col3"].unique()

array([2, 4], dtype=int64)

In [55]:
dd["Col1"].unique()

array([1], dtype=int64)

In [56]:
df.head()

Col1  Col2  Col3  Col4
Row1     0     1     2     3
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

In [57]:
df["Col1"].unique()

array([ 0,  4,  8, 12, 16])

In [59]:
df["Col1"].unique()

array([ 0,  4,  8, 12, 16])

In [60]:
df>2

Col1   Col2   Col3  Col4
Row1  False  False  False  True
Row2   True   True   True  True
Row3   True   True   True  True
Row4   True   True   True  True
Row5   True   True   True  True

In [61]:
df[df["Col2"]>2] #row which has greater than 2 values

Col1  Col2  Col3  Col4
Row2     4     5     6     7
Row3     8     9    10    11
Row4    12    13    14    15
Row5    16    17    18    19

# StringIO   #in memory file object

In [72]:
from io import StringIO

In [74]:
de = pd.read_csv("mercedesbenz.csv")

In [75]:
de.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [76]:
type(de)

pandas.core.frame.DataFrame

In [77]:
data1 = ('col1,col2,col3\n'
        'x,y,1\n'
        'a,b,2\n'
        'c,d,3')

In [79]:
type(data1)  #above is string data type

str

In [80]:
StringIO(data1) #in memory file format object #convert string to normal file reading format

In [81]:
pd.read_csv(StringIO(data1))  

col1 col2  col3
0    x    y     1
1    a    b     2
2    c    d     3

In [83]:
pd.read_csv(StringIO(data1), usecols = ["col1","col2"]) #usecols parameter is used to read data with particular colums

col1 col2
0    x    y
1    a    b
2    c    d

In [84]:
df = pd.read_csv("mercedesbenz.csv", usecols = ["X0","X1","X2","X3","X4","X5"]) #usecols parameter is used to read data with particular colums

In [85]:
df

X0 X1  X2 X3 X4  X5
0      k  v  at  a  d   u
1      k  t  av  e  d   y
2     az  w   n  c  d   x
3     az  t   n  f  d   x
4     az  v   n  f  d   h
...   .. ..  .. .. ..  ..
4204  ak  s  as  c  d  aa
4205   j  o   t  d  d  aa
4206  ak  v   r  a  d  aa
4207  al  r   e  f  d  aa
4208   z  r  ae  c  d  aa

[4209 rows x 6 columns]

In [86]:
df.to_csv("test.csv") #to convert the above data to csv format.. plz check in jypter folder test.csv file will be created

In [ ]:
df.to_csv("test.csv", index = False) #no index number will saved in the test.csv file

In [89]:
data2 = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11,')

In [92]:
dg = pd.read_csv(StringIO(data2))

In [93]:
dg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int64  
 1   b       3 non-null      int64  
 2   c       3 non-null      int64  
 3   d       2 non-null      float64
dtypes: float64(1), int64(3)
memory usage: 224.0 bytes


In [98]:
dh = pd.read_csv(StringIO(data2), dtype = "object")  #object is nothing but string #here we are converting int to object (string)

In [99]:
dh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   a       3 non-null      object
 1   b       3 non-null      object
 2   c       3 non-null      object
 3   d       2 non-null      object
dtypes: object(4)
memory usage: 224.0+ bytes


In [103]:
data3 = ('a,b,c,d\n'
        '1,2,3,4\n'
        '5,6,7,8\n'
        '9,10,11,')

In [104]:
dh = pd.read_csv(StringIO(data3), dtype= {"a" : int, "b": float, "c" : int}) #to convert different column to different datatype
dh

a     b   c    d
0  1   2.0   3  4.0
1  5   6.0   7  8.0
2  9  10.0  11  NaN

In [105]:
dh.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   a       3 non-null      int32  
 1   b       3 non-null      float64
 2   c       3 non-null      int32  
 3   d       2 non-null      float64
dtypes: float64(2), int32(2)
memory usage: 200.0 bytes


In [106]:
dh.dtypes

a      int32
b    float64
c      int32
d    float64
dtype: object

In [95]:
dg.isnull().sum()

a    0
b    0
c    0
d    1
dtype: int64

In [96]:
dg.head()

a   b   c    d
0  1   2   3  4.0
1  5   6   7  8.0
2  9  10  11  NaN

In [97]:
dg["a"][1] #to access 2 row 1 colum data

5

In [107]:
#use index cols and usecols
data5 = ('index,a,b,c\n'
        '4,apple,bat,5.7\n'
        '8,ornage,cow,10')

In [109]:
pd.read_csv(StringIO(data5), usecols = ['b','c'], index_col = 0)

index       a    b     c
0      4   apple  bat   5.7
1      8  ornage  cow  10.0

In [110]:
pd.read_csv(StringIO(data5), usecols = ['b','c'], index_col = 0)

c
b        
bat   5.7
cow  10.0

In [114]:
pd.read_csv("https://download.bls.gov/pub/time.series/cu/cu.item", sep = "\t") #check the format of website in sepate chrome tab

item_code                                          item_name  \
0         AA0                               All items - old base   
1        AA0R  Purchasing power of the consumer dollar - old ...   
2         SA0                                          All items   
3        SA0E                                             Energy   
4       SA0L1                                All items less food   
..        ...                                                ...   
395   SSEA011                                  College textbooks   
396   SSEE041                                        Smartphones   
397  SSFV031A           Food at elementary and secondary schools   
398   SSGE013                                 Infants' equipment   
399   SSHJ031                                 Infants' furniture   

     display_level selectable  sort_sequence  
0                0          T              2  
1                0          T            400  
2                0          T              1  
3                1          T            375  
4                1          T            359  
..             ...        ...            ...  
395              3          T            314  
396              4          T            335  
397              3          T            122  
398              3          T            356  
399              3          T            165  

[400 rows x 5 columns]

In [115]:
pd.read_csv("https://download.bls.gov/pub/time.series/cu/cu.item", sep = "\t").to_csv("govdata.csv") #converting aobve file to govdata.csv